### ISSUE TITLE
How to initialize?

### ISSUE THREAD

**Issue by AmadeusSys** [biessek/vue-facebook-account-kit#1]
`AccountKit.login(
      'PHONE', 
      {countryCode: countryCode, phoneNumber: phoneNumber}, // will use default values if not specified
      loginCallback
    );`
is error

**Comment by AmadeusSys** [comment]
Can provide demo

**Comment by biessek** [comment]
as soon as possible I will try to add a demo to the repositories,..
for now, you may have a look to some of these available on the internet, like this:
[https://github.com/biessek/fb-account-kit-example](https://github.com/biessek/fb-account-kit-example)
or this  
[https://github.com/dca/facebook-account-kit-demo](https://github.com/dca/facebook-account-kit-demo)  
or this
[https://auth0.com/blog/facebook-account-kit-passwordless-authentication/](https://auth0.com/blog/facebook-account-kit-passwordless-authentication/)
remember, this lib is just a wrapper to add the facebook account kit in the vue way;
