### ISSUE TITLE
Can't change loginType

### ISSUE THREAD

**Issue by OnlyC** [biessek/vue-facebook-account-kit#2]
**Problem:**
In the example: https://github.com/biessek/fb-account-kit-example
when I add a button "login by Email", I need to change loginType prop in the component.
If I directly change it, Vue throw a warning that I should use data method to change prop dynamically.
If I use data and v-bind:loginType = loginType on the component's props, it doesn't reload the component, it only changed if I press button again.

**Solutions:**
There are 2 options:
 - Create watcher for the component.
 - Modify the login method to accept 3 variable, the first is loginType.

**Comment by biessek** [comment]
I changed the example to use date in dynamic type change.
Be free to PR if you feel better.
