### ISSUE TITLE
New version 0.1.1 not working

### ISSUE THREAD

**Issue by myowinthein** [biessek/vue-facebook-account-kit#6]
## What Happen
The new __version 0.1.1__ show the error  ```This dependency was not found vue-facebook-account-kit in ./plugins/vue-facebook-account-kit.js. To install it, you can run: npm install --save vue-facebook-account-kit```

__I've already installed and still not solve when install again. When I switch to _version 0.1.0_,  everything work well again expect the display cannot change bug.__

**Comment by norbybaru** [comment]
Was this issue resolved? having same issue with version `0.1.1`. has to drop to `0.1.0`

**Comment by biessek** [comment]
Sorry for the inconvenience, this problem does not occur in the latest v0.1.2 version
